# Generated by Django 2.2 on 2020-04-25 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(default=0)),
                ('expense', models.IntegerField(default=0)),
                ('task_text', models.CharField(max_length=200)),
                ('date_recorded', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
