# Generated by Django 2.2 on 2020-05-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsandServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(verbose_name='transaction date')),
                ('date_updated', models.DateTimeField(verbose_name='latest_transaction_date')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(max_length=200)),
                ('transaction_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ps4.ProductsandServices')),
            ],
        ),
        migrations.DeleteModel(
            name='Playstation',
        ),
    ]
