# Generated by Django 2.2 on 2020-05-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0002_auto_20200518_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_type',
        ),
    ]
