# Generated by Django 2.2 on 2020-05-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0004_transactions_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_id',
            new_name='productsandservices',
        ),
    ]
