# Generated by Django 2.2 on 2020-06-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0007_transactions_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_liability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'income'), ('Expense', 'expense')], default='Income', max_length=10),
        ),
    ]
