# Generated by Django 2.2 on 2020-06-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0008_auto_20200618_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='description',
        ),
    ]
