# Generated by Django 2.2 on 2020-06-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0009_remove_transactions_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='is_liability',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'income'), ('Expense', 'expense'), ('Liability', 'liability')], default='Income', max_length=10),
        ),
    ]
