# Generated by Django 2.2 on 2020-10-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0010_auto_20200618_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
