# Generated by Django 2.2 on 2020-10-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0011_auto_20201024_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
