# Generated by Django 2.2 on 2020-10-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0013_auto_20201025_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'income'), ('Expense', 'expense'), ('Liability', 'liability')], default='GAMING', max_length=10),
        ),
    ]
