# Generated by Django 2.2 on 2020-11-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0016_auto_20201110_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
