# Generated by Django 2.2 on 2020-11-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0017_auto_20201110_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('item', models.CharField(max_length=10)),
                ('transactions', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ps4.Transactions')),
            ],
        ),
    ]
