# Generated by Django 2.2 on 2020-11-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0018_savings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='item',
            new_name='expense',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='transactions',
        ),
        migrations.AddField(
            model_name='savings',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='savings',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
