# Generated by Django 2.2 on 2020-11-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0019_auto_20201111_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='expense',
            field=models.CharField(default='Null', max_length=10),
        ),
    ]
