# Generated by Django 2.2 on 2020-11-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0020_auto_20201115_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='savings',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
