# Generated by Django 2.2 on 2021-02-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0021_auto_20201121_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsandservices',
            options={'verbose_name': 'productsandservice', 'verbose_name_plural': 'productsandservices'},
        ),
    ]
