# Generated by Django 2.2 on 2021-02-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0022_auto_20210210_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'income'), ('Expense', 'expense'), ('Liability', 'liability')], default='income', max_length=10),
        ),
    ]
