# Generated by Django 2.2 on 2021-02-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0023_auto_20210212_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'income'), ('Expense', 'expense'), ('Savings', 'savings')], default='income', max_length=10),
        ),
    ]
