# Generated by Django 2.2 on 2021-02-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0024_auto_20210212_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
